set_property SRC_FILE_INFO {cfile:C:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/dac_example/dac_example.srcs/constrs_1/new/constr.xdc rfile:../../../dac_example.srcs/constrs_1/new/constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS     } [get_ports { clk_n }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS     } [get_ports { clk_p }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C27   IOSTANDARD DEFAULT } [get_ports { out_n[0] }]; #IO_L13N_T2_MRCC_16 Sch=fmc_la_n[00]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D27   IOSTANDARD DEFAULT } [get_ports { out_p[0] }]; #IO_L13P_T2_MRCC_16 Sch=fmc_la_p[00]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C26   IOSTANDARD DEFAULT } [get_ports { out_n[1] }]; #IO_L11N_T1_SRCC_16 Sch=fmc_la_n[01]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D26   IOSTANDARD DEFAULT } [get_ports { out_p[1] }]; #IO_L11P_T1_SRCC_16 Sch=fmc_la_p[01]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G30   IOSTANDARD DEFAULT } [get_ports { out_n[2] }]; #IO_L24N_T3_16 Sch=fmc_la_n[02]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H30   IOSTANDARD DEFAULT } [get_ports { out_p[2] }]; #IO_L24P_T3_16 Sch=fmc_la_p[02]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E30   IOSTANDARD DEFAULT } [get_ports { out_n[3] }]; #IO_L18N_T2_16 Sch=fmc_la_n[03]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E29   IOSTANDARD DEFAULT } [get_ports { out_p[3] }]; #IO_L18P_T2_16 Sch=fmc_la_p[03]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H27   IOSTANDARD DEFAULT } [get_ports { out_n[4] }]; #IO_L23N_T3_16 Sch=fmc_la_n[04]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H26   IOSTANDARD DEFAULT } [get_ports { out_p[4] }]; #IO_L23P_T3_16 Sch=fmc_la_p[04]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A30   IOSTANDARD DEFAULT } [get_ports { out_n[5] }]; #IO_L17N_T2_16 Sch=fmc_la_n[05]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B30   IOSTANDARD DEFAULT } [get_ports { out_p[5] }]; #IO_L17P_T2_16 Sch=fmc_la_p[05]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C30   IOSTANDARD DEFAULT } [get_ports { out_n[6] }]; #IO_L16N_T2_16 Sch=fmc_la_n[06]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D29   IOSTANDARD DEFAULT } [get_ports { out_p[6] }]; #IO_L16P_T2_16 Sch=fmc_la_p[06]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E25   IOSTANDARD DEFAULT } [get_ports { out_n[7] }]; #IO_L3N_T0_DQS_16 Sch=fmc_la_n[07]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F25   IOSTANDARD DEFAULT } [get_ports { out_p[7] }]; #IO_L3P_T0_DQS_16 Sch=fmc_la_p[07]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B29   IOSTANDARD DEFAULT } [get_ports { out_n[8] }]; #IO_L15N_T2_DQS_16 Sch=fmc_la_n[08]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C29   IOSTANDARD DEFAULT } [get_ports { out_p[8] }]; #IO_L15P_T2_DQS_16 Sch=fmc_la_p[08]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A28   IOSTANDARD DEFAULT } [get_ports { out_n[9] }]; #IO_L9N_T1_DQS_16 Sch=fmc_la_n[09]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B28   IOSTANDARD DEFAULT } [get_ports { out_p[9] }]; #IO_L9P_T1_DQS_16 Sch=fmc_la_p[09]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A27   IOSTANDARD DEFAULT } [get_ports { out_n[10] }]; #IO_L7N_T1_16 Sch=fmc_la_n[10]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B27   IOSTANDARD DEFAULT } [get_ports { out_p[10] }]; #IO_L7P_T1_16 Sch=fmc_la_p[10]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A26   IOSTANDARD DEFAULT } [get_ports { out_n[11] }]; #IO_L10N_T1_16 Sch=fmc_la_n[11]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A25   IOSTANDARD DEFAULT } [get_ports { out_p[11] }]; #IO_L10P_T1_16 Sch=fmc_la_p[11]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E26   IOSTANDARD DEFAULT } [get_ports { out_n[12] }]; #IO_L5N_T0_16 Sch=fmc_la_n[12]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F26   IOSTANDARD DEFAULT } [get_ports { out_p[12] }]; #IO_L5P_T0_16 Sch=fmc_la_p[12]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D24   IOSTANDARD DEFAULT } [get_ports { out_n[13] }]; #IO_L4N_T0_16 Sch=fmc_la_n[13]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E24   IOSTANDARD DEFAULT } [get_ports { out_p[13] }]; #IO_L4P_T0_16 Sch=fmc_la_p[13]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B24   IOSTANDARD DEFAULT } [get_ports { out_n[14] }]; #IO_L8N_T1_16 Sch=fmc_la_n[14]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C24   IOSTANDARD DEFAULT } [get_ports { out_p[14] }]; #IO_L8P_T1_16 Sch=fmc_la_p[14]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A23   IOSTANDARD DEFAULT } [get_ports { out_n[15] }]; #IO_L1N_T0_16 Sch=fmc_la_n[15]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B23   IOSTANDARD DEFAULT } [get_ports { out_p[15] }]; #IO_L1P_T0_16 Sch=fmc_la_p[15]
