# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_v2.xci
# IP: The module: 'fpga_model_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i0/fpga_model_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i0 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i1/fpga_model_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i1 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i2/fpga_model_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i2 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i3/fpga_model_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i3 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i4/fpga_model_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i4 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i5/fpga_model_c_addsub_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i5 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i6/fpga_model_c_addsub_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i6 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_counter_binary_v12_0_i0/fpga_model_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==fpga_model_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_counter_binary_v12_0_i1/fpga_model_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==fpga_model_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i0/fpga_model_dist_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_dist_mem_gen_i0 || ORIG_REF_NAME==fpga_model_dist_mem_gen_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i1/fpga_model_dist_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_dist_mem_gen_i1 || ORIG_REF_NAME==fpga_model_dist_mem_gen_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_mult_gen_v12_0_i0/fpga_model_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_mult_gen_v12_0_i0 || ORIG_REF_NAME==fpga_model_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_mult_gen_v12_0_i1/fpga_model_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_mult_gen_v12_0_i1 || ORIG_REF_NAME==fpga_model_mult_gen_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i0/fpga_model_dist_mem_gen_i0_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i1/fpga_model_dist_mem_gen_i1_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/constrs/fpga_model.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_model_v2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_v2.xci
# IP: The module: 'fpga_model_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i0/fpga_model_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i0 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i1/fpga_model_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i1 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i2/fpga_model_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i2 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i3/fpga_model_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i3 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i4/fpga_model_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i4 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i5/fpga_model_c_addsub_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i5 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_addsub_v12_0_i6/fpga_model_c_addsub_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_addsub_v12_0_i6 || ORIG_REF_NAME==fpga_model_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_counter_binary_v12_0_i0/fpga_model_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==fpga_model_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_c_counter_binary_v12_0_i1/fpga_model_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==fpga_model_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i0/fpga_model_dist_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_dist_mem_gen_i0 || ORIG_REF_NAME==fpga_model_dist_mem_gen_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i1/fpga_model_dist_mem_gen_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_dist_mem_gen_i1 || ORIG_REF_NAME==fpga_model_dist_mem_gen_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_mult_gen_v12_0_i0/fpga_model_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_mult_gen_v12_0_i0 || ORIG_REF_NAME==fpga_model_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_mult_gen_v12_0_i1/fpga_model_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_model_mult_gen_v12_0_i1 || ORIG_REF_NAME==fpga_model_mult_gen_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i0/fpga_model_dist_mem_gen_i0_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/fpga_model_dist_mem_gen_i1/fpga_model_dist_mem_gen_i1_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/fpga_model_v2/constrs/fpga_model.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_model_v2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
