# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/example_sg.xci
# IP: The module: 'example_sg' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/untitled_c_addsub_v12_0_i0/untitled_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==untitled_c_addsub_v12_0_i0 || ORIG_REF_NAME==untitled_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/untitled_c_addsub_v12_0_i1/untitled_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==untitled_c_addsub_v12_0_i1 || ORIG_REF_NAME==untitled_c_addsub_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/constrs/untitled.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_sg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/example_sg.xci
# IP: The module: 'example_sg' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/untitled_c_addsub_v12_0_i0/untitled_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==untitled_c_addsub_v12_0_i0 || ORIG_REF_NAME==untitled_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/untitled_c_addsub_v12_0_i1/untitled_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==untitled_c_addsub_v12_0_i1 || ORIG_REF_NAME==untitled_c_addsub_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/example_sg/constrs/untitled.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_sg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
