# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_0.xci
# IP: The module: 'model_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i0/model_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i0 || ORIG_REF_NAME==model_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i1/model_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i1 || ORIG_REF_NAME==model_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i2/model_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i2 || ORIG_REF_NAME==model_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i3/model_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i3 || ORIG_REF_NAME==model_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i4/model_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i4 || ORIG_REF_NAME==model_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_counter_binary_v12_0_i0/model_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==model_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_counter_binary_v12_0_i1/model_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==model_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_dist_mem_gen_i0/model_dist_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_dist_mem_gen_i0 || ORIG_REF_NAME==model_dist_mem_gen_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_mult_gen_v12_0_i0/model_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_mult_gen_v12_0_i0 || ORIG_REF_NAME==model_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_dist_mem_gen_i0/model_dist_mem_gen_i0_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/constrs/model.xdc
# XDC: The top module name and the constraint reference have the same name: 'model_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_0.xci
# IP: The module: 'model_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i0/model_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i0 || ORIG_REF_NAME==model_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i1/model_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i1 || ORIG_REF_NAME==model_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i2/model_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i2 || ORIG_REF_NAME==model_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i3/model_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i3 || ORIG_REF_NAME==model_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_addsub_v12_0_i4/model_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_addsub_v12_0_i4 || ORIG_REF_NAME==model_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_counter_binary_v12_0_i0/model_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==model_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_c_counter_binary_v12_0_i1/model_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==model_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_dist_mem_gen_i0/model_dist_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_dist_mem_gen_i0 || ORIG_REF_NAME==model_dist_mem_gen_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_mult_gen_v12_0_i0/model_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==model_mult_gen_v12_0_i0 || ORIG_REF_NAME==model_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/model_dist_mem_gen_i0/model_dist_mem_gen_i0_ooc.xdc

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/model_0/constrs/model.xdc
# XDC: The top module name and the constraint reference have the same name: 'model_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
