# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/second_case.xci
# IP: The module: 'second_case' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i0/rb_dmm_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i0 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i1/rb_dmm_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i1 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i2/rb_dmm_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i2 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i3/rb_dmm_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i3 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_counter_binary_v12_0_i0/rb_dmm_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==rb_dmm_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_mult_gen_v12_0_i0/rb_dmm_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_mult_gen_v12_0_i0 || ORIG_REF_NAME==rb_dmm_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/constrs/rb_dmm.xdc
# XDC: The top module name and the constraint reference have the same name: 'second_case'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/second_case.xci
# IP: The module: 'second_case' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i0/rb_dmm_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i0 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i1/rb_dmm_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i1 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i2/rb_dmm_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i2 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_addsub_v12_0_i3/rb_dmm_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_addsub_v12_0_i3 || ORIG_REF_NAME==rb_dmm_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_c_counter_binary_v12_0_i0/rb_dmm_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==rb_dmm_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/rb_dmm_mult_gen_v12_0_i0/rb_dmm_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rb_dmm_mult_gen_v12_0_i0 || ORIG_REF_NAME==rb_dmm_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/second_case/constrs/rb_dmm.xdc
# XDC: The top module name and the constraint reference have the same name: 'second_case'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
