# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo.xci
# IP: The module: 'builtin_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo.xci
# IP: The module: 'builtin_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/DACZC706/DACZC706.srcs/sources_1/ip/builtin_fifo/builtin_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'builtin_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
