# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/WAVE_GEN.xci
# IP: The module: 'WAVE_GEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i0/wave_generator_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i1/wave_generator_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i2/wave_generator_c_counter_binary_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/constrs/wave_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'WAVE_GEN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/WAVE_GEN.xci
# IP: The module: 'WAVE_GEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i0/wave_generator_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i1/wave_generator_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/wave_generator_c_counter_binary_v12_0_i2/wave_generator_c_counter_binary_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wave_generator_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==wave_generator_c_counter_binary_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DACGenesys2/workspace/zc706_dac/zc706_dac.srcs/sources_1/ip/WAVE_GEN/constrs/wave_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'WAVE_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
